spring:
  application:
    name: clothingstore

  datasource:
    url: jdbc:mysql://localhost:3306/clothingstore
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update